matrix:
  include:
    - language: php
      php: 5.6
      before_script: "composer install"
      script: "composer test"

    - language: php
      php: 7.1
      before_script: "composer install"
      script: "composer test"

    - language: node_js
      node_js: "node"
