version: '3.1'

services:
  wordpress:
    image: wordpress:5.3
    ports:
        - 3600:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/themes/dones

  db:
    image: mariadb:10.4.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - data:/var/lib/mysql

volumes:
  wordpress:
  data:
